feature: create theme change component
Minnemi/minnemi-front pull request #27
Opened 2023-06-03 01:17 UTC by guilherme-biancardi

Criação do componente e funções da mudança de tema

Foram instaladas as seguintes dependências:

- vue-use-core: [https://vueuse.org](url)
- mdi/js: [https://www.npmjs.com/package/@mdi/js](url)
- vue-icon: [https://www.npmjs.com/package/@jamescoyle/vue-icon
](url)

o tema já está sendo alterado automaticamente de acordo com a preferência do usuário **(salvo no local storage)**.

issue: #14

2023-06-03 02:05 UTC, viniciuscosmome requested changes
👀

2023-06-03 02:05 UTC, viniciuscosmome commented on src/stores/appStore.js
> +import { useBase64, useColorMode, useLocalStorage } from '@vueuse/core';
Esse método não parece estar sendo usado: `useBase64`

```suggestion
import { useColorMode, useLocalStorage } from '@vueuse/core';
```

2023-06-14 17:19 UTC, HugoVersiani submitted a review, later dismissed

2023-06-19 00:31 UTC, viniciuscosmome approved these changes
LGTM 🚀

2023-06-19 00:32 UTC, merged